version: '3.8'

services:
  port-checker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - FLASK_ENV=production
      - SERVICE_DOMAIN=${SERVICE_DOMAIN:-localhost:8080}
      - API_TOKEN=${API_TOKEN:-your-secret-api-token-here}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-3600}
      - PORTS_TO_CHECK=${PORTS_TO_CHECK:-80,443}
      - PORT_CHECK_TIMEOUT=${PORT_CHECK_TIMEOUT:-5}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 